/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'
import { Route as ServicesPortfolioWebsitesRouteImport } from './routes/services.portfolio-websites'
import { Route as ServicesLandingPagesRouteImport } from './routes/services.landing-pages'
import { Route as ServicesEcommerceRouteImport } from './routes/services.ecommerce'
import { Route as ServicesCustomWebsitesRouteImport } from './routes/services.custom-websites'
import { Route as ServicesCustomSoftwareRouteImport } from './routes/services.custom-software'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorkRoute,
} as any)
const ServicesPortfolioWebsitesRoute =
  ServicesPortfolioWebsitesRouteImport.update({
    id: '/portfolio-websites',
    path: '/portfolio-websites',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesLandingPagesRoute = ServicesLandingPagesRouteImport.update({
  id: '/landing-pages',
  path: '/landing-pages',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesEcommerceRoute = ServicesEcommerceRouteImport.update({
  id: '/ecommerce',
  path: '/ecommerce',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCustomWebsitesRoute = ServicesCustomWebsitesRouteImport.update({
  id: '/custom-websites',
  path: '/custom-websites',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCustomSoftwareRoute = ServicesCustomSoftwareRouteImport.update({
  id: '/custom-software',
  path: '/custom-software',
  getParentRoute: () => ServicesRoute,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/process': typeof ProcessRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/work': typeof WorkRouteWithChildren
  '/services/custom-software': typeof ServicesCustomSoftwareRoute
  '/services/custom-websites': typeof ServicesCustomWebsitesRoute
  '/services/ecommerce': typeof ServicesEcommerceRoute
  '/services/landing-pages': typeof ServicesLandingPagesRoute
  '/services/portfolio-websites': typeof ServicesPortfolioWebsitesRoute
  '/work/$slug': typeof WorkSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/work/': typeof WorkIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/process': typeof ProcessRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/services/custom-software': typeof ServicesCustomSoftwareRoute
  '/services/custom-websites': typeof ServicesCustomWebsitesRoute
  '/services/ecommerce': typeof ServicesEcommerceRoute
  '/services/landing-pages': typeof ServicesLandingPagesRoute
  '/services/portfolio-websites': typeof ServicesPortfolioWebsitesRoute
  '/work/$slug': typeof WorkSlugRoute
  '/services': typeof ServicesIndexRoute
  '/work': typeof WorkIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/process': typeof ProcessRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/work': typeof WorkRouteWithChildren
  '/services/custom-software': typeof ServicesCustomSoftwareRoute
  '/services/custom-websites': typeof ServicesCustomWebsitesRoute
  '/services/ecommerce': typeof ServicesEcommerceRoute
  '/services/landing-pages': typeof ServicesLandingPagesRoute
  '/services/portfolio-websites': typeof ServicesPortfolioWebsitesRoute
  '/work/$slug': typeof WorkSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/work/': typeof WorkIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/disclaimer'
    | '/faq'
    | '/industries'
    | '/pricing'
    | '/privacy-policy'
    | '/process'
    | '/refund-policy'
    | '/services'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/work'
    | '/services/custom-software'
    | '/services/custom-websites'
    | '/services/ecommerce'
    | '/services/landing-pages'
    | '/services/portfolio-websites'
    | '/work/$slug'
    | '/services/'
    | '/work/'
    | '/api/public/contact'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/disclaimer'
    | '/faq'
    | '/industries'
    | '/pricing'
    | '/privacy-policy'
    | '/process'
    | '/refund-policy'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/services/custom-software'
    | '/services/custom-websites'
    | '/services/ecommerce'
    | '/services/landing-pages'
    | '/services/portfolio-websites'
    | '/work/$slug'
    | '/services'
    | '/work'
    | '/api/public/contact'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/disclaimer'
    | '/faq'
    | '/industries'
    | '/pricing'
    | '/privacy-policy'
    | '/process'
    | '/refund-policy'
    | '/services'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/work'
    | '/services/custom-software'
    | '/services/custom-websites'
    | '/services/ecommerce'
    | '/services/landing-pages'
    | '/services/portfolio-websites'
    | '/work/$slug'
    | '/services/'
    | '/work/'
    | '/api/public/contact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FaqRoute: typeof FaqRoute
  IndustriesRoute: typeof IndustriesRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProcessRoute: typeof ProcessRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  WorkRoute: typeof WorkRouteWithChildren
  ApiPublicContactRoute: typeof ApiPublicContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof WorkRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof WorkRoute
    }
    '/services/portfolio-websites': {
      id: '/services/portfolio-websites'
      path: '/portfolio-websites'
      fullPath: '/services/portfolio-websites'
      preLoaderRoute: typeof ServicesPortfolioWebsitesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/landing-pages': {
      id: '/services/landing-pages'
      path: '/landing-pages'
      fullPath: '/services/landing-pages'
      preLoaderRoute: typeof ServicesLandingPagesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ecommerce': {
      id: '/services/ecommerce'
      path: '/ecommerce'
      fullPath: '/services/ecommerce'
      preLoaderRoute: typeof ServicesEcommerceRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/custom-websites': {
      id: '/services/custom-websites'
      path: '/custom-websites'
      fullPath: '/services/custom-websites'
      preLoaderRoute: typeof ServicesCustomWebsitesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/custom-software': {
      id: '/services/custom-software'
      path: '/custom-software'
      fullPath: '/services/custom-software'
      preLoaderRoute: typeof ServicesCustomSoftwareRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesCustomSoftwareRoute: typeof ServicesCustomSoftwareRoute
  ServicesCustomWebsitesRoute: typeof ServicesCustomWebsitesRoute
  ServicesEcommerceRoute: typeof ServicesEcommerceRoute
  ServicesLandingPagesRoute: typeof ServicesLandingPagesRoute
  ServicesPortfolioWebsitesRoute: typeof ServicesPortfolioWebsitesRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCustomSoftwareRoute: ServicesCustomSoftwareRoute,
  ServicesCustomWebsitesRoute: ServicesCustomWebsitesRoute,
  ServicesEcommerceRoute: ServicesEcommerceRoute,
  ServicesLandingPagesRoute: ServicesLandingPagesRoute,
  ServicesPortfolioWebsitesRoute: ServicesPortfolioWebsitesRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface WorkRouteChildren {
  WorkSlugRoute: typeof WorkSlugRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkSlugRoute: WorkSlugRoute,
  WorkIndexRoute: WorkIndexRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  FaqRoute: FaqRoute,
  IndustriesRoute: IndustriesRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProcessRoute: ProcessRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  WorkRoute: WorkRouteWithChildren,
  ApiPublicContactRoute: ApiPublicContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
